server:
port: 8080

spring:
  datasource:
    username: root
    password: pass
    url:
      jdbc:mysql://localhost:3306/bulletin_board?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false